version: '3.7'

services:
  lanchonete:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app/src
    working_dir: /app/src
    environment:
      - POSTGRESQL_CONNECTION_STRING_PAGAMENTO=${POSTGRESQL_CONNECTION_STRING_PAGAMENTO}
    networks:
      - default

networks:
  default:
    name: lanchonete_pagamento_network
