apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pagamento-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pagamento-app
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
